### ISSUE TITLE
eurekaInstanceConfigBean conflict

### ISSUE THREAD

**Issue by ericadowling** [pivotal-cf/spring-cloud-services-connector#121]
The following error occurs when using Service Registry with a Gateway app in Spring Boot 2.1:
`2019-03-13T16:08:05.15+0100 [APP/PROC/WEB/0] OUT The bean 'eurekaInstanceConfigBean', defined in class path resource [io/pivotal/spring/cloud/service/eureka/EurekaInstanceAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.class] and overriding is disabled.`

From looking into the issue, it looks like the eurekaInstanceConfigBean is used in both `spring-cloud-services-spring-connector` and `spring-cloud-starter-netflix-eureka-client` which are both sub-dependencies of `spring-cloud-services-starter-service-registry`.  However, there seems to only be a conflict between these when the `starter-gateway`  or `gateway-core` dependency is also present(which also contains a `netflix-eureka-client` sub-dependency). If I exclude the `netflix-eureka-client` dependency from the gateway dependency, it doesn’t make a difference. But if I exclude same from the service-registry dependency, the error doesn’t appear, but I don’t know if excluding this will cause further issues down the line.

I’ve reproduced this error with a [gateway sample app](https://github.com/ericadowling/spring-cloud-gateway-sample). This error occurs when pushing the app to PCF. It requires redis-server to run. The versions used in this app are as follows:
- spring-boot-starter-parent = 2.1.2.RELEASE
- spring-cloud.version = Greenwich.RELEASE
- spring-cloud-services-starter-service-registry = 2.1.1.RELEASE

**Comment by anishpanthi** [comment]
I'm also facing same issue.

**Comment by dyroberts** [comment]
@anishpanthi Thanks for your feedback. It would expedite the process significantly if you were able to create a small github repo with some sample code that reproduces the issue.

**Comment by emreavsar** [comment]
is this still an open issue? how are the people using cloud gateway with service discovery within pcf then?

**Comment by falti** [comment]
Is there any progress on this?

**Comment by anishpanthi** [comment]
Its working good for me now. Sorry I was not able to update earlier.
