### ISSUE TITLE
PropertyMaskingContextInitializer prevents configuration of "keys-to-sanitize"

### ISSUE THREAD

**Issue by datagitlies** [pivotal-cf/spring-cloud-services-connector#127]
There are two parts to this issue:

1. In my application the [`PropertyMaskingContextInitializer`](https://github.com/pivotal-cf/spring-cloud-services-connector/blob/master/spring-cloud-services-spring-connector/src/main/java/io/pivotal/spring/cloud/service/config/PropertyMaskingContextInitializer.java) fails to find a `PropertySource` with the name "bootstrapProperties" of type `CompositePropertySource`
    - I may be missing something, but I'm not sure what this property source is or where it is supposed to come from.
2. The [`PropertyMaskingContextInitializer`](https://github.com/pivotal-cf/spring-cloud-services-connector/blob/master/spring-cloud-services-spring-connector/src/main/java/io/pivotal/spring/cloud/service/config/PropertyMaskingContextInitializer.java) is adding a `PropertySource` with the name "management.endpoint.env.keys-to-sanitize" of type `PropertiesPropertySource` **at the  highest precedence.**

The end result is that the `/env` actuator endpoint is not fully masked / sanitized and I'm stuck because I am unable to override the `management.endpoint.env.keys-to-sanitize` property in `application.yml` or by any other means since it will always be at a lower precedence than what the [`PropertyMaskingContextInitializer`](https://github.com/pivotal-cf/spring-cloud-services-connector/blob/master/spring-cloud-services-spring-connector/src/main/java/io/pivotal/spring/cloud/service/config/PropertyMaskingContextInitializer.java) provides.

**Comment by datagitlies** [comment]
any concerns if I open a pull request to change [PropertyMaskingContextInitializer.java:84](https://github.com/pivotal-cf/spring-cloud-services-connector/blob/master/spring-cloud-services-spring-connector/src/main/java/io/pivotal/spring/cloud/service/config/PropertyMaskingContextInitializer.java#L84) from this:

```java
environment.getPropertySources().addFirst(envKeysToSanitize);
```

to this
```
environment.getPropertySources().addLast(envKeysToSanitize);
```

???

**Comment by dyroberts** [comment]
Hi @datagitlies. First, thanks for your valuable feedback. I should mention that this library is deprecated; so it's recommended that you switch to our latest starter library. That is, as long as you're using an SCS tile of version 3.0 or newer. See here: https://docs.pivotal.io/spring-cloud-services/3-1/common/client-dependencies.html. As far as this issue goes, it would be helpful if you created a small example in a git repo that exposes the problem that you're experiencing. It's not clear to me what's going on with your app based on the original description in this issue.

**Comment by datagitlies** [comment]
@dyroberts thanks for the information. Since this library is deprecated I went and found the same issue over in the [spring-cloud-services-starters](https://github.com/pivotal-cf/spring-cloud-services-starters) library.  The [VaultPropertyMaskingContextInitializer](https://github.com/pivotal-cf/spring-cloud-services-starters/blob/master/spring-cloud-services-config-client-autoconfigure/src/main/java/io/pivotal/spring/cloud/config/client/VaultPropertyMaskingContextInitializer.java#L96) in `3.1.0.RELEASE` suffers from the same issue.  It's adding a `PropertySource` with the name "management.endpoint.env.keys-to-sanitize" of type `PropertiesPropertySource` **at the highest precedence** 

```
environment.getPropertySources().addFirst(envKeysToSanitize);
```

I'll try to articulate the issue better with an example. I assume you'd prefer I open a new issue [over there](https://github.com/pivotal-cf/spring-cloud-services-starters/issues), correct?

**Comment by dyroberts** [comment]
@datagitlies That would work well. Thanks!

**Comment by datagitlies** [comment]
@dyroberts see pivotal-cf/spring-cloud-services-starters#122
