### ISSUE TITLE
EurekaInstanceAutoConfiguration & RelaxedPropertyResolver

### ISSUE THREAD

**Issue by pawelkalbrun** [pivotal-cf/spring-cloud-services-connector#33]
Hi 
EurekaInstanceAutoConfiguration class has a dependency on RelaxedPropertyResolver(through SanitizingEurekaInstanceConfigBean).  Spring boot 2 removed that class.  
What is the roadmap for services-connectors, when are you planning on supporting Spring boot 2? 

Looks like spring cloud eureka auto config has been already updated https://github.com/spring-cloud/spring-cloud-netflix/commit/8d1a82f9b434bcf2e49e21063cdb937f9479aa40#diff-fd50bdd6abee6268d81bd6a5d0fc4dcd which is not a case for pivotal

Any feedback very much appreciated.

**Comment by daniellavoie** [comment]
Hi

As of now, the latest version of Spring Cloud we support is `Dalston`. Spring Boot 2 support will be delivered after Spring Cloud `Finchley` is shipped. `Finchley.RELEASE` is planned for [mid-January](https://github.com/spring-cloud/spring-cloud-release/milestone/39). SCS Connectors should be released simultaneously.
