### ISSUE TITLE
Publish SCS Connectors 2.0.0.RC2

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/spring-cloud-services-connector#50]
Based on Finchley.RC2 when it is released.

**Comment by Bwvolleyball** [comment]
Any update / expected timelines for 2.0.0.RC2 now that Finchley.RC2 is out? 😄

**Comment by royclarkson** [comment]
Thanks for checking in. We’re working on validating all the features and are hoping to have a release out soon.

**Comment by royclarkson** [comment]
This release is now available in the milestone repository
