### ISSUE TITLE
Application Rename URI

### ISSUE THREAD

**Issue by austinpilz** [pivotal-cf/spring-cloud-services-connector#57]
I'm using the spring-cloud-services-connector in order to accomplish Eureka connectivity on cloud foundry. When our app deploys, after a successful health check, our PCF renames our applications.

Example: ```Renaming application example-app-development-dark to example-app-development...```

I'm using ```${vcap.application.uris[0]}``` in my application-dev.yaml file in order to grab the URI for purposes of Eureka registration on the client side. Once the application renames itself, that variable isn't updated in the Eureka config. The Eureka clients are stuck associating with their dark url, which makes them unusable. Is there a way to accomplish refreshing that value in the client Eureka config?

**Comment by azizabah** [comment]
We had a similar issue. You might want to look here [Eureka issue](https://github.com/spring-cloud/spring-cloud-netflix/issues/1851)

**Comment by csterwa** [comment]
@austinpilz by default the SCS Connectors use the `spring.application.name` property to register a service. If I understand correctly, you would like there to be a way to override this property? Potentially with another property value?

Could you provide the PCF manifest.yml and application properties that you are using along with the Gradle/Maven build file for us to take a look at?

**Comment by austinpilz** [comment]
@csterwa It's not the application name actually, it's the URI the application is registering with Eureka. On deploy, Spring tells Eureka about the injected URI, which is the "-dark" endpoint. Then once deploy succeeds, the application is re-mapped from "-dark" to the regular endpoint, but Eureka never receives that change.

**Comment by csterwa** [comment]
@austinpilz I've prioritized this to be looked at over the next few weeks. Considering my understanding of how this works this may result in a significant change to current behavior. If you have any thoughts on possible solutions please let us know.

**Comment by austinpilz** [comment]
@csterwa Here's my full explanation in case it helps:

At the beginning of the blue/green deployment, my applications URI is test-app-dark.example.com

During deployment, the Spring Cloud Services Connector grabs the URI from the environment variable ```${vcap.application.uris[0]}``` and associates with Eureka successfully.

Upon the successful health check of the application, our application URL is mapped from ```test-app-dark.example.com``` -> ```test-app.example.com```. The issue arises that Eureka can't pick up on this change as the variable value has already been grabbed. From there on out, the Eureka registry has my "dark" endpoint permanently associated.

My workaround has been to just hard code the hostname in the Eureka config:
```eureka.instance.hostname: test-app.example.com``` and ```metadata-map:
      CF_APP_GUID: ${vcap.application.application_id}
      CF_INSTANCE_INDEX: ${CF_INSTANCE_INDEX}```, which allows my service to service connections to work successfully.

**Comment by ojhughes** [comment]
Hi @austinpilz, we are encouraging customers to start thinking about using Envoy for use cases such as this. Polyglot service discovery is now enabled by default in PAS 2.2 and should support blue green deployment, as described in this blog post https://www.cloudfoundry.org/blog/polyglot-service-discovery-container-networking-cloud-foundry/

Can you let me know your thoughts?

**Comment by austinpilz** [comment]
Hi @ojhughes, thanks for sharing that link. It was a good read! With some of the apps I'm working with, they're integrated fully with Eureka and I'd hopefully like to remain using it for now. I'd love to see a solution to Eureka and PCF's re-mapping issue, as it works fantastically otherwise.

**Comment by ojhughes** [comment]
just had another look at this. I guess we could mark the bean https://github.com/pivotal-cf/spring-cloud-services-connector/blob/master/spring-cloud-services-spring-connector/src/main/java/io/pivotal/spring/cloud/service/eureka/EurekaInstanceAutoConfiguration.java#L92-L106 with `@RefreshScope` then call `/refresh` whenever the environment changes.

Doesn't feel like an ideal solution but I can't think of another way.

**Comment by ojhughes** [comment]
Closing this for now because it seems like it will be a lot of work to fix. We always welcome ideas or contributions so feel free to reopen this issue if any ideas come up. Thanks!
