### ISSUE TITLE
Missing metadata for Spring Boot configuration keys

### ISSUE THREAD

**Issue by bclozel** [pivotal-cf/spring-cloud-services-connector#67]
When configuration keys are deduced from a `@ConfigurationProperties` class, Spring Boot's `spring-boot-configuration-processor` will create a metadata file at compile time; this file is being used by various tools, especially IDEs.

If configuration keys are not declared in a configuration properties class, project maintainers should document those manually in a `META-INF/additional-spring-configuration-metadata.json` file. You can read more about this in [the Spring Boot reference documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-additional-metadata) and check [metadata in Spring Boot itself](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json).

It looks like this project is using configuration keys that are missing that metadata information:
* `spring.cloud.config.client.oauth2.client-id` (used in `ConfigClientOAuth2BootstrapConfiguration`)
* `eureka.client.oauth2.clientId` (used in `EurekaOAuth2AutoConfiguration `)

Could you document those configuration keys?

To make things easier, you can:
1. Create locally a configuration properties class with that property
2. run the compiler
3. fetch the generated metadata in the `spring-configuration-metadata.json` file
4. Copy that in the `additional-spring-configuration-metadata.json` one (and create such a file if doesn't exist already).

**Comment by royclarkson** [comment]
@bclozel thanks! we'll resolve this in the next release.

**Comment by csterwa** [comment]
@bclozel this was resolved in the just posted SCS Connector/Starters `2.0.1.RELEASE` thanks to @royclarkson.
