### ISSUE TITLE
application.yml should not be packaged

### ISSUE THREAD

**Issue by stadler** [pivotal-cf/spring-cloud-services-connector#69]
The spring-cloud-services-connector as of version 2.0.0.RELEASE contains an [application.yml](https://github.com/pivotal-cf/spring-cloud-services-connector/blob/master/spring-cloud-services-spring-connector/src/main/resources/application.yml) that is packaged as part of the final jar.
This means that it will be picked up by spring boot applications using this library. 
By picking this up the loggers of `org.springframework.web` and `org.springframework.security` will be logging to DEBUG which is certainly not the intention of most of the users of this library.

I guess the debug stuff should be removed and the yml file should be renamed to something library specific e.g. `application-spring-cloud-service-connector.yml` and referenced explicitly within this library, to avoid accidental picking up of this configuration file.

**Comment by csterwa** [comment]
@stadler Thank you for logging this issue. Our team is working to resolve this ASAP and will be publishing a `2.0.1.RELEASE` version soon.

**Comment by royclarkson** [comment]
This appears to have been mistakenly added to the main resources and instead the file should have been included in the test resources.

**Comment by csterwa** [comment]
@stadler the SCS Connector/Starters `2.0.1.RELEASE` was just posted to Maven Central. This includes the removal of the application.properties file from the release artifacts thanks to @royclarkson.
