### ISSUE TITLE
Upgrade to Spring Cloud Greenwich.RC2

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/spring-cloud-services-connector#88]
This would include upgrading not only Spring Cloud to Greenwich.RC2 but also most recent Spring Boot 2.1 release.

**Comment by habuma** [comment]
As half-expected, simply upgrading to Greenwich.RC2 resulted in 43 out of 56 of the connectors' tests failing. A sampling of about a dozen of those failures showed the same issue:

```java.lang.AbstractMethodError
	at org.springframework.core.OrderComparator.findOrder(OrderComparator.java:142)```

Although there were one or two other failures related to bean creation which may or may not be related.

**Comment by habuma** [comment]
Upgrading to Boot 2.1.1.RELEASE addressed most of these issues, although there are still 11 failing tests. A sampling of most of them says that they are all the same...

```Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'io.pivotal.spring.cloud.service.config.ConfigClientOAuth2BootstrapConfiguration' available: expected single matching bean but found 2: configClientOAuth2BootstrapConfiguration,io.pivotal.spring.cloud.service.config.ConfigClientOAuth2BootstrapConfiguration
```

More investigation is required, but at least on the surface, this resembles a similar issue I encountered when upgrading SCS 3 to Greenwich snapshots.
