### ISSUE TITLE
Publish SCS Connectors version 2.1.0.M1

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/spring-cloud-services-connector#89]
After the upgrade to Greenwich #88 then we should publish a milestone.

depends on #88

**Comment by habuma** [comment]
Just a comment (that may or may not apply here): Upgrading SCS 3.0 to Greenwich sounded easy, but there were some gotchas, largely with regard to changes in Spring Security OAuth and Spring CredHub. Again, these may not apply to connectors, but it's worth considering that there might be surprises and a solid test of the connectors would be advised.

**Comment by habuma** [comment]
I'm leaving this in backlog for now (so as not to have 2 in-progress issues with my face on them), but there's no point in anyone else picking this issue up until after I complete the work on #88.
