### ISSUE TITLE
Add 2.1.0.RELEASE to start.spring.io

### ISSUE THREAD

**Issue by csterwa** [pivotal-cf/spring-cloud-services-connector#93]
Depends on Spring Cloud Greenwich.RELEASE and Spring Boot 2.1.x.

depends on #92

**Comment by habuma** [comment]
The PR has been created: https://github.com/spring-io/start.spring.io/pull/46

Will close this issue once the PR has been merged and I've had a chance to test it.

**Comment by habuma** [comment]
This is now live at start.spring.io.
