### ISSUE TITLE
PlainTextOAuth2ConfigClient fails to fetch files from Vault backed Config Server

### ISSUE THREAD

**Issue by Walliee** [pivotal-cf/spring-cloud-services-connector#95]
`X-Config-Token` is mandatory on all requests to Spring Config Server when Vault is a property source. 
`PlainTextOAuth2ConfigClient` doesn't set this header even when it's available on `ConfigClientProperties` and the request to config server fails with the following message:
```
Missing required header: X-Config-Token
```

I created a [sample](https://github.com/Walliee/spring-cloud-services-connector-vault-header-issue/tree/master) that replicates this issue.

**Comment by csterwa** [comment]
@Walliee thank you for creating this issue. Currently, Spring Cloud Services does not support fetching plain text files from HashiCorp Vault. Can you provide more detail on your use case for using Vault to store plain text files? This may be a feature request we had not considered previously.

**Comment by habuma** [comment]
Just to clarify: Is the plain text file stored in the Vault backend or in a Git backend?

**Comment by kelapure** [comment]
The plain text file is stored in the git backend.

**Comment by habuma** [comment]
Okay, thanks. That's what I imagined. I asked because if it were in the Vault backend, that'd be a slightly different twist that I wasn't expecting.

**Comment by Walliee** [comment]
Our use-case currently is not to fetch files from Vault. Although, I can already see the value in that. 

Our config server is setup with composite backend (Vault + Git) with vault first in the list.

**Comment by csterwa** [comment]
@Walliee thanks. I misinterpreted the original issue.

**Comment by Walliee** [comment]
@csterwa I already created a [PR](https://github.com/pivotal-cf/spring-cloud-services-connector/pull/96) that resolves this issue. Please feel free to review and merge.

**Comment by Walliee** [comment]
I am on the Pivotal CLA although it doesn't seem to be on the checklist for this project.
